# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'get_patient_inf_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Get_Patient_Inf_Dialog(object):
    def setupUi(self, Get_Patient_Inf_Dialog):
        Get_Patient_Inf_Dialog.setObjectName("Get_Patient_Inf_Dialog")
        Get_Patient_Inf_Dialog.resize(283, 193)
        self.gridLayout_2 = QtWidgets.QGridLayout(Get_Patient_Inf_Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.bed_nub_l = QtWidgets.QLabel(Get_Patient_Inf_Dialog)
        self.bed_nub_l.setObjectName("bed_nub_l")
        self.gridLayout.addWidget(self.bed_nub_l, 3, 0, 1, 1)
        self.age_text = QtWidgets.QLineEdit(Get_Patient_Inf_Dialog)
        self.age_text.setObjectName("age_text")
        self.gridLayout.addWidget(self.age_text, 2, 1, 1, 1)
        self.gender_text = QtWidgets.QLineEdit(Get_Patient_Inf_Dialog)
        self.gender_text.setObjectName("gender_text")
        self.gridLayout.addWidget(self.gender_text, 1, 1, 1, 1)
        self.name_text = QtWidgets.QLineEdit(Get_Patient_Inf_Dialog)
        self.name_text.setObjectName("name_text")
        self.gridLayout.addWidget(self.name_text, 0, 1, 1, 1)
        self.take_pack_I = QtWidgets.QLabel(Get_Patient_Inf_Dialog)
        self.take_pack_I.setObjectName("take_pack_I")
        self.gridLayout.addWidget(self.take_pack_I, 4, 0, 1, 1)
        self.take_pack_text = QtWidgets.QLineEdit(Get_Patient_Inf_Dialog)
        self.take_pack_text.setObjectName("take_pack_text")
        self.gridLayout.addWidget(self.take_pack_text, 4, 1, 1, 1)
        self.name_l = QtWidgets.QLabel(Get_Patient_Inf_Dialog)
        self.name_l.setObjectName("name_l")
        self.gridLayout.addWidget(self.name_l, 0, 0, 1, 1)
        self.bed_nub_text = QtWidgets.QLineEdit(Get_Patient_Inf_Dialog)
        self.bed_nub_text.setObjectName("bed_nub_text")
        self.gridLayout.addWidget(self.bed_nub_text, 3, 1, 1, 1)
        self.buttonBox_l = QtWidgets.QDialogButtonBox(Get_Patient_Inf_Dialog)
        self.buttonBox_l.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox_l.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_l.setObjectName("buttonBox_l")
        self.gridLayout.addWidget(self.buttonBox_l, 6, 0, 1, 2)
        self.gender_l = QtWidgets.QLabel(Get_Patient_Inf_Dialog)
        self.gender_l.setObjectName("gender_l")
        self.gridLayout.addWidget(self.gender_l, 1, 0, 1, 1)
        self.age_l = QtWidgets.QLabel(Get_Patient_Inf_Dialog)
        self.age_l.setObjectName("age_l")
        self.gridLayout.addWidget(self.age_l, 2, 0, 1, 1)
        self.picture_number_I = QtWidgets.QLabel(Get_Patient_Inf_Dialog)
        self.picture_number_I.setObjectName("picture_number_I")
        self.gridLayout.addWidget(self.picture_number_I, 5, 0, 1, 1)
        self.picture_number_text = QtWidgets.QLineEdit(Get_Patient_Inf_Dialog)
        self.picture_number_text.setObjectName("picture_number_text")
        self.gridLayout.addWidget(self.picture_number_text, 5, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Get_Patient_Inf_Dialog)
        self.buttonBox_l.accepted.connect(Get_Patient_Inf_Dialog.accept)
        self.buttonBox_l.rejected.connect(Get_Patient_Inf_Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Get_Patient_Inf_Dialog)

    def retranslateUi(self, Get_Patient_Inf_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Get_Patient_Inf_Dialog.setWindowTitle(_translate("Get_Patient_Inf_Dialog", "病人信息"))
        self.bed_nub_l.setText(_translate("Get_Patient_Inf_Dialog", "病床号："))
        self.take_pack_I.setText(_translate("Get_Patient_Inf_Dialog", "采取部位:"))
        self.name_l.setText(_translate("Get_Patient_Inf_Dialog", "姓名："))
        self.gender_l.setText(_translate("Get_Patient_Inf_Dialog", "性别："))
        self.age_l.setText(_translate("Get_Patient_Inf_Dialog", "年龄："))
        self.picture_number_I.setText(_translate("Get_Patient_Inf_Dialog", "涂片号:"))
