# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'getCutImgDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cut_img_dialog(object):
    def setupUi(self, cut_img_dialog):
        cut_img_dialog.setObjectName("cut_img_dialog")
        cut_img_dialog.resize(696, 442)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(cut_img_dialog)
        self.horizontalLayout_2.setContentsMargins(6, -1, -1, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeWidget = CutTreeWidget(cut_img_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.treeWidget.header().setVisible(False)
        self.verticalLayout.addWidget(self.treeWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.save_root_line_edit = QtWidgets.QLineEdit(cut_img_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_root_line_edit.sizePolicy().hasHeightForWidth())
        self.save_root_line_edit.setSizePolicy(sizePolicy)
        self.save_root_line_edit.setObjectName("save_root_line_edit")
        self.horizontalLayout.addWidget(self.save_root_line_edit)
        self.choose_save_root_button = QtWidgets.QPushButton(cut_img_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choose_save_root_button.sizePolicy().hasHeightForWidth())
        self.choose_save_root_button.setSizePolicy(sizePolicy)
        self.choose_save_root_button.setMinimumSize(QtCore.QSize(150, 0))
        self.choose_save_root_button.setObjectName("choose_save_root_button")
        self.horizontalLayout.addWidget(self.choose_save_root_button)
        self.horizontalLayout.setStretch(0, 9)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.decide_button_box = QtWidgets.QDialogButtonBox(cut_img_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.decide_button_box.sizePolicy().hasHeightForWidth())
        self.decide_button_box.setSizePolicy(sizePolicy)
        self.decide_button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.decide_button_box.setObjectName("decide_button_box")
        self.verticalLayout.addWidget(self.decide_button_box)
        self.verticalLayout.setStretch(0, 10)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(cut_img_dialog)
        self.decide_button_box.accepted.connect(cut_img_dialog.close)
        self.decide_button_box.rejected.connect(cut_img_dialog.close)
        self.decide_button_box.accepted.connect(cut_img_dialog.accept)
        self.decide_button_box.rejected.connect(cut_img_dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(cut_img_dialog)

    def retranslateUi(self, cut_img_dialog):
        _translate = QtCore.QCoreApplication.translate
        cut_img_dialog.setWindowTitle(_translate("cut_img_dialog", "Dialog"))
        self.save_root_line_edit.setText(_translate("cut_img_dialog", "默认保存于所选病人的categories文件夹，如需改动点击右边的按键选择路径"))
        self.choose_save_root_button.setText(_translate("cut_img_dialog", "选择保存路径"))
from itemBase.cutTreeWidget import CutTreeWidget
